Repository moasis-team/monolithic-be, pull requests merged in 2023-01, with the labels that each got.

#3 #1 - 공통 클래스 및 패키지 개발
  build.gradle
  src/main/java/site/moasis/monolithicbe/application/controller/Controller.java
  src/main/java/site/moasis/monolithicbe/common/exception/BaseException.java
  src/main/java/site/moasis/monolithicbe/common/exception/EntityNotFoundException.java
  src/main/java/site/moasis/monolithicbe/common/exception/IllegalStatusException.java
  src/main/java/site/moasis/monolithicbe/common/exception/InvalidParamException.java
  src/main/java/site/moasis/monolithicbe/common/response/CommonControllerAdvice.java
  src/main/java/site/moasis/monolithicbe/common/response/CommonResponse.java
  src/main/java/site/moasis/monolithicbe/common/response/ErrorCode.java
  src/main/java/site/moasis/monolithicbe/common/validator/ValidationResult.java
  src/main/java/site/moasis/monolithicbe/domain/article/dto/ArticleDto.java
  src/main/java/site/moasis/monolithicbe/domain/article/entity/Article.java
  src/main/java/site/moasis/monolithicbe/domain/article/repository/ArticleRepository.java
  src/main/java/site/moasis/monolithicbe/domain/article/service/ArticleReadService.java
  src/main/java/site/moasis/monolithicbe/domain/article/service/ArticleWriteService.java
  src/main/java/site/moasis/monolithicbe/domain/comment/dto/CommentDto.java
  src/main/java/site/moasis/monolithicbe/domain/comment/entity/Comment.java
  src/main/java/site/moasis/monolithicbe/domain/comment/repository/CommentRepository.java
  src/main/java/site/moasis/monolithicbe/domain/comment/service/CommentReadService.java
  src/main/java/site/moasis/monolithicbe/domain/comment/service/CommentWriteService.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/dto/UserAccountDto.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/entity/UserAccount.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/repository/UserAccountRepository.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/service/UserAccountService.java
Labels: enhancement

#4 Feature/#2 데이터베이스 연결
  .gitignore
  build.gradle
  src/main/resources/application-prod.yaml
  src/main/resources/application.properties
Labels: enhancement

#7 #5 - 도커 파일 프로파일 수정
  Dockerfile
Labels: enhancement

#9 #8 - 댓글 CRD 기능
  build.gradle
  src/main/java/site/moasis/monolithicbe/application/controller/CommentController.java
  src/main/java/site/moasis/monolithicbe/common/response/CommonControllerAdvice.java
  src/main/java/site/moasis/monolithicbe/common/response/ErrorCode.java
  src/main/java/site/moasis/monolithicbe/domain/comment/dto/CommentDto.java
  src/main/java/site/moasis/monolithicbe/domain/comment/entity/Comment.java
  src/main/java/site/moasis/monolithicbe/domain/comment/repository/CommentRepository.java
  src/main/java/site/moasis/monolithicbe/domain/comment/service/CommentReadService.java
  src/main/java/site/moasis/monolithicbe/domain/comment/service/CommentWriteService.java
Labels: documentation, enhancement

#14 #13 - 댓글 기능 고도화
  src/main/java/site/moasis/monolithicbe/domain/comment/entity/Comment.java
  src/main/java/site/moasis/monolithicbe/domain/comment/repository/CommentRepository.java
  src/main/java/site/moasis/monolithicbe/domain/comment/service/CommentReadService.java
  src/main/java/site/moasis/monolithicbe/domain/comment/service/CommentWriteService.java
Labels: enhancement

#11 #10 - 사용자 회원 가입 기능 구현
  .gitignore
  build.gradle
  src/main/java/site/moasis/monolithicbe/application/configuration/CorsFilterConfig.java
  src/main/java/site/moasis/monolithicbe/application/configuration/JwtConfig.java
  src/main/java/site/moasis/monolithicbe/application/configuration/JwtSecurityConfig.java
  src/main/java/site/moasis/monolithicbe/application/configuration/SecurityConfig.java
  src/main/java/site/moasis/monolithicbe/application/controller/UserAccountController.java
  src/main/java/site/moasis/monolithicbe/common/exception/DuplicatedEmailException.java
  src/main/java/site/moasis/monolithicbe/common/response/CommonControllerAdvice.java
  src/main/java/site/moasis/monolithicbe/common/response/ErrorCode.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/JwtAccessDeniedHandler.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/JwtAuthenticationEntryPoint.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/JwtFilter.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/TokenProvider.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/UserRole.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/dto/UserAccountDto.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/entity/UserAccount.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/entity/UserDetailsImpl.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/repository/UserAccountRepository.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/service/UserAccountReadService.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/service/UserAccountService.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/service/UserAccountWriteService.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/service/UserDetailsServiceImpl.java
  src/main/resources/application.yml
Labels: enhancement

#19 #13 - Conflict fix
  src/main/java/site/moasis/monolithicbe/application/controller/CommentController.java
  src/main/java/site/moasis/monolithicbe/application/controller/Controller.java
  src/main/java/site/moasis/monolithicbe/common/exception/DuplicatedEmailException.java
  src/main/java/site/moasis/monolithicbe/common/response/ErrorCode.java
  src/main/java/site/moasis/monolithicbe/domain/comment/dto/CommentDto.java
  src/main/java/site/moasis/monolithicbe/domain/comment/entity/Comment.java
  src/main/java/site/moasis/monolithicbe/domain/comment/repository/CommentRepository.java
  src/main/java/site/moasis/monolithicbe/domain/comment/service/CommentInfo.java
  src/main/java/site/moasis/monolithicbe/domain/comment/service/CommentInfoMapper.java
  src/main/java/site/moasis/monolithicbe/domain/comment/service/CommentReadService.java
  src/main/java/site/moasis/monolithicbe/domain/comment/service/CommentWriteService.java
  src/main/java/site/moasis/monolithicbe/domain/comment/vo/CommentVo.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/service/UserAccountWriteService.java
Labels: duplicate, enhancement

#24 #23 - 전체 패키지 구조 변경
  src/main/generated/site/moasis/monolithicbe/service/CommentInfoMapperImpl.java
  src/main/java/site/moasis/monolithicbe/common/exception/BusinessException.java
  src/main/java/site/moasis/monolithicbe/common/exception/ConstraintViolationResolver.java
  src/main/java/site/moasis/monolithicbe/common/exception/ErrorCode.java
  src/main/java/site/moasis/monolithicbe/common/exception/FieldErrorDetail.java
  src/main/java/site/moasis/monolithicbe/common/exception/GlobalExceptionHandler.java
  src/main/java/site/moasis/monolithicbe/common/exception/SelfValidating.java
  src/main/java/site/moasis/monolithicbe/common/validator/ValidationResult.java
  src/main/java/site/moasis/monolithicbe/configuration/CorsFilterConfig.java
  src/main/java/site/moasis/monolithicbe/configuration/JwtConfig.java
  src/main/java/site/moasis/monolithicbe/configuration/JwtSecurityConfig.java
  src/main/java/site/moasis/monolithicbe/configuration/SecurityConfig.java
  src/main/java/site/moasis/monolithicbe/controller/article/ArticleController.java
  src/main/java/site/moasis/monolithicbe/controller/comment/CommentController.java
  src/main/java/site/moasis/monolithicbe/controller/common/CommonResponse.java
  src/main/java/site/moasis/monolithicbe/controller/useraccount/UserAccountController.java
  src/main/java/site/moasis/monolithicbe/domain/comment/Comment.java
  src/main/java/site/moasis/monolithicbe/domain/comment/CommentDto.java
  src/main/java/site/moasis/monolithicbe/domain/comment/dto/CommentDto.java
  src/main/java/site/moasis/monolithicbe/domain/comment/vo/CommentVo.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/service/UserAccountWriteService.java
  src/main/java/site/moasis/monolithicbe/infrastructure/CommentRepository.java
  src/main/java/site/moasis/monolithicbe/service/CommentCommand.java
  src/main/java/site/moasis/monolithicbe/service/CommentInfo.java
  src/main/java/site/moasis/monolithicbe/service/CommentInfoMapper.java
  src/main/java/site/moasis/monolithicbe/service/CommentReadService.java
  src/main/java/site/moasis/monolithicbe/service/CommentWriteService.java
Labels: enhancement

#27 #26 -이메일 인증
  build.gradle
  src/main/generated/site/moasis/monolithicbe/service/CommentInfoMapperImpl.java
  src/main/java/site/moasis/monolithicbe/common/exception/ErrorCode.java
  src/main/java/site/moasis/monolithicbe/common/message/UserMessage.java
  src/main/java/site/moasis/monolithicbe/controller/useraccount/UserAccountController.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/dto/UserAccountDto.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/service/UserEmailService.java
  src/main/resources/application-prod.yml
Labels: enhancement

#33 #12 - 댓글 예외 처리 및 댓글 컨트롤러 삭제 리팩토링
  src/main/java/site/moasis/monolithicbe/application/configuration/LocaleConfig.java
  src/main/java/site/moasis/monolithicbe/common/exception/GlobalExceptionHandler.java
  src/main/java/site/moasis/monolithicbe/controller/comment/CommentController.java
  src/main/java/site/moasis/monolithicbe/controller/common/CommonResponse.java
  src/main/java/site/moasis/monolithicbe/service/CommentCommand.java
  src/main/java/site/moasis/monolithicbe/service/CommentWriteService.java
  src/main/resources/business-errors.properties
  src/main/resources/messages/message.properties
  src/main/resources/messages/message_ko_KR.properties
  src/main/resources/validation-errors.properties
Labels: enhancement

#32 #30 - JPQL적용
  src/main/java/site/moasis/monolithicbe/infrastructure/CommentRepository.java
  src/main/java/site/moasis/monolithicbe/service/CommentReadService.java
  src/main/java/site/moasis/monolithicbe/service/CommentWriteService.java
Labels: documentation, enhancement

#28 #17 - 리프레쉬토큰 적용
  src/main/java/site/moasis/monolithicbe/configuration/JwtConfig.java
  src/main/java/site/moasis/monolithicbe/configuration/JwtSecurityConfig.java
  src/main/java/site/moasis/monolithicbe/configuration/SecurityConfig.java
  src/main/java/site/moasis/monolithicbe/controller/useraccount/UserAccountController.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/AccessTokenManager.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/JwtFilter.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/RefreshTokenManager.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/TokenManager.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/dto/UserAccountDto.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/entity/UserAccount.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/repository/UserAccountRepository.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/service/UserAccountReadService.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/service/UserAccountWriteService.java
  src/main/resources/application-prod.yml
Labels: enhancement

#36 Fix/#35 - 머지 후 파생된 에러 수정
  build.gradle
  src/main/java/site/moasis/monolithicbe/controller/useraccount/UserAccountController.java
Labels: fix

#37 #26 Mail, Jwt 설정 변경 및 추가
  build.gradle
  src/main/java/site/moasis/monolithicbe/configuration/AppProperties.java
  src/main/java/site/moasis/monolithicbe/configuration/MailConfig.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/AccessTokenManager.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/RefreshTokenManager.java
  src/main/java/site/moasis/monolithicbe/domain/useraccount/service/UserEmailService.java
  src/main/resources/application-prod.yml
Labels: documentation, enhancement

#40 #39 - 테스트 구조 작성 및 에러코드, 예외처리 테스트 작성
  src/test/java/site/moasis/monolithicbe/integration/Common/ConstraintViolationResolverIntegrationTest.java
  src/test/java/site/moasis/monolithicbe/unit/common/exception/ErrorCodeTest.java
  src/test/resources/application.yml
  src/test/resources/test-validation-errors.properties
Labels: enhancement
